# Assignment

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

from pdb import set_trace
import math

In [2]:
# Import 

import numpy as np
import matplotlib.pyplot as plt
from degree_freedom_queen import *
from degree_freedom_king1 import *
from degree_freedom_king2 import *
from generate_game import *
from Chess_env import *


size_board = 4

## The Environment

You can find the environment in the file Chess_env, which contains the class Chess_env. To define an object, you need to provide the board size considered as input. In our example, size_board=4. 
Chess_env is composed by the following methods:

1. Initialise_game. The method initialises an episode by placing the three pieces considered (Agent's king and queen, enemy's king) in the chess board. The outputs of the method are described below in order.

     S $\;$ A matrix representing the board locations filled with 4 numbers: 0, no piece in that position; 1, location of the 
     agent's king; 2 location of the queen; 3 location of the enemy king.
     
     X $\;$ The features, that is the input to the neural network. See the assignment for more information regarding the            definition of the features adopted. To personalise this, go into the Features method of the class Chess_env() and change        accordingly.
     
     allowed_a $\;$ The allowed actions that the agent can make. The agent is moving a king, with a total number of 8                possible actions, and a queen, with a total number of $(board_{size}-1)\times 8$ actions. The total number of possible actions correspond      to the sum of the two, but not all actions are allowed in a given position (movements to locations outside the borders or      against chess rules). Thus, the variable allowed_a is a vector that is one (zero) for an action that the agent can (can't)      make. Be careful, apply the policy considered on the actions that are allowed only.
     

2. OneStep. The method performs a one step update of the system. Given as input the action selected by the agent, it updates the chess board by performing that action and the response of the enemy king (which is a random allowed action in the settings considered). The first three outputs are the same as for the Initialise_game method, but the variables are computed for the position reached after the update of the system. The fourth and fifth outputs are:

     R $\;$ The reward. To change this, look at the OneStep method of the class where the rewards are set.
     
     Done $\;$ A variable that is 1 if the episode has ended (checkmate or draw).
     
     
3. Features. Given the chessboard position, the method computes the features.

This information and a quick analysis of the class should be all you need to get going. The other functions that the class exploits are uncommented and constitute an example on how not to write a python code. You can take a look at them if you want, but it is not necessary.






In [3]:
## INITIALISE THE ENVIRONMENT

env=Chess_Env(size_board)

In [4]:
## PRINT 5 STEPS OF AN EPISODE CONSIDERING A RANDOM AGENT

S,X,allowed_a=env.Initialise_game()                       # INTIALISE GAME

print(S)                                                  # PRINT CHESS BOARD (SEE THE DESCRIPTION ABOVE)

print('check? ',env.check)                                # PRINT VARIABLE THAT TELLS IF ENEMY KING IS IN CHECK (1) OR NOT (0)
print('dofk2 ',np.sum(env.dfk2_constrain).astype(int))    # PRINT THE NUMBER OF LOCATIONS THAT THE ENEMY KING CAN MOVE TO


for i in range(5):
    
    a,_=np.where(allowed_a==1)                  # FIND WHAT THE ALLOWED ACTIONS ARE
    a_agent=np.random.permutation(a)[0]         # MAKE A RANDOM ACTION

#     set_trace()
    S,X,allowed_a,R,Done=env.OneStep(a_agent)   # UPDATE THE ENVIRONMENT
    
    
    ## PRINT CHESS BOARD AND VARIABLES
    print('')
    print(S)
    print(R,'', Done)
    print('check? ',env.check)
    print('dofk2 ',np.sum(env.dfk2_constrain).astype(int))
    
    
    # TERMINATE THE EPISODE IF Done=True (DRAW OR CHECKMATE)
    if Done:
        break
        


[[0 0 3 0]
 [0 0 0 0]
 [0 0 1 2]
 [0 0 0 0]]
check?  0
dofk2  0

[[0 0 3 0]
 [0 0 0 0]
 [0 1 0 2]
 [0 0 0 0]]
0.0  1
check?  0
dofk2  0


In [5]:
# PERFORM N_episodes=1000 EPISODES MAKING RANDOM ACTIONS AND COMPUTE THE AVERAGE REWARD AND NUMBER OF MOVES 

S,X,allowed_a=env.Initialise_game()
N_episodes=1000

# VARIABLES WHERE TO SAVE THE FINAL REWARD IN AN EPISODE AND THE NUMBER OF MOVES 
R_save_random = np.zeros([N_episodes, 1])
N_moves_save_random = np.zeros([N_episodes, 1])

for n in range(N_episodes):
    
    S,X,allowed_a=env.Initialise_game()     # INITIALISE GAME
    Done=0                                  # SET Done=0 AT THE BEGINNING
    i=1                                     # COUNTER FOR THE NUMBER OF ACTIONS (MOVES) IN AN EPISODE
    
    # UNTIL THE EPISODE IS NOT OVER...(Done=0)
    while Done==0:
        
        # SAME AS THE CELL BEFORE, BUT SAVING THE RESULTS WHEN THE EPISODE TERMINATES 
        
        a,_=np.where(allowed_a==1)
        a_agent=np.random.permutation(a)[0]

        S,X,allowed_a,R,Done=env.OneStep(a_agent)
        
        
        if Done:
            
            R_save_random[n]=np.copy(R)
            N_moves_save_random[n]=np.copy(i)

            break

        i=i+1                               # UPDATE THE COUNTER



# AS YOU SEE, THE PERFORMANCE OF A RANDOM AGENT ARE NOT GREAT, SINCE THE MAJORITY OF THE POSITIONS END WITH A DRAW 
# (THE ENEMY KING IS NOT IN CHECK AND CAN'T MOVE)

print('Random_Agent, Average reward:',np.mean(R_save_random),'Number of steps: ',np.mean(N_moves_save_random))



Random_Agent, Average reward: 0.217 Number of steps:  6.828


## Defining a simple NN 

In [32]:
class NeuralNetwork: 
    
    def __init__(self, Xavier_init= True, layer_type = 'ReLU',number_of_layers = 1, number_of_neurons_per_layer = [200], output_size = 1, input_size = 58):
        
        self.Ws = []
        self.bs = []
        self.layer_type = layer_type
        
        if Xavier_init:
            W1 = np.random.randn(number_of_neurons_per_layer[0], input_size) * np.sqrt(1 / (input_size))  # first layer 
            self.Ws.append(W1)
            for i in range(1, number_of_layers):
            
                W = np.random.randn(number_of_neurons_per_layer[i], number_of_neurons_per_layer[i-1]) * np.sqrt(1 / (number_of_neurons_per_layer[i-1]))
                self.Ws.append(W)
                
            W_out = np.random.randn(output_size, number_of_neurons_per_layer[-1]) * np.sqrt(1 / (number_of_neurons_per_layer[-1]))
            self.Ws.append(W_out)
            
            
        else: 
            print('Not Implemented :=(')
            

        for i in range(number_of_layers): 
            b = np.zeros((number_of_neurons_per_layer[i],))
            self.bs.append(b)
        b_out = np.zeros((output_size,))
        self.bs.append(b_out)
        
        
    def forward(self, x0): 
        
        layer_out = x0
        for i in range(len(self.Ws) - 1):
            layer_out_pre_activation = np.dot(self.Ws[i], layer_out) + self.bs[i]   # calculate Wx + b
            layer_out = 1/(1+np.exp(-layer_out_pre_activation))                     # apply sigmoid funciton 
            
        return layer_out_pre_activation  # because the last layer should have no sigmoid! 
    
    def _forward_batch(self, x0s): 
        outputs = [] 
        intermediate_outputs_list = [] 
        
        for x0 in x0s:
            output, intermediate_outputs = self._forward(x0)
            
            outputs.append(output)
            intermediate_outputs_list.append(intermediate_outputs)
        
        return outputs, intermediate_outputs_list
            
            
    
    
    def _forward(self, x0): 
        
        intermediate_outputs = [] 
        layer_out = x0
        intermediate_outputs.append(layer_out)
        
        if self.layer_type == 'ReLU': 
            for i in range(len(self.Ws) - 1):
                layer_out_pre_activation = np.dot(self.Ws[i], layer_out) + self.bs[i]   # calculate Wx + b
                layer_out = layer_out_pre_activation.copy()
                layer_out[layer_out< 0] = 0    # for ReLU: make all positions <0 equal to 0
                intermediate_outputs.append(layer_out)
                
            layer_out = np.dot(self.Ws[-1], layer_out) + self.bs[-1]
            intermediate_outputs.append(layer_out)
            
            return layer_out, intermediate_outputs
                
                
            
        else: 
            print('entering sigmoid part of forward')

            for i in range(len(self.Ws) - 1):
                layer_out_pre_activation = np.dot(self.Ws[i], layer_out) + self.bs[i]   # calculate Wx + b
                layer_out = 1/(1+np.exp(-layer_out_pre_activation))                     # apply sigmoid funciton
                intermediate_outputs.append(layer_out)

            layer_out = np.dot(self.Ws[-1], layer_out) + self.bs[-1]
            intermediate_outputs.append(layer_out)
            
            return layer_out, intermediate_outputs
    
    
    def backward(self, x0s, outputs, desired_outputs, intermediate_outputs_list): 
        
        
        dWs = [np.zeros(shape = self.Ws[i].shape) for i in range(len(self.Ws))]
        dbiases = [np.zeros(shape = self.bs[i].shape) for i in range(len(self.bs))]  
        
        
        
        for j in range(len(x0s)): 
            
            output = outputs[j]
            desired_output = desired_outputs[j]
            intermediate_outputs = intermediate_outputs_list[j]
            x0 = x0s[j]
            
            
            error_signal = desired_output - output

            if self.layer_type == 'ReLU': 
                
                for i in reversed(range(len(self.Ws))):
                    if i == len(self.Ws) - 1:
                        delta = error_signal                  # error signal -> L,  delta x input at layer-> Derivative at that layer    :=>    dW = derivative * lr 
                        
                    else: 
                        intermediate_outputs_copy = intermediate_outputs[i+1].copy()
                        intermediate_outputs_copy[intermediate_outputs_copy < 0] = 0 
                        intermediate_outputs_copy[intermediate_outputs_copy > 0 ] = 1
                        
                        delta = intermediate_outputs_copy * error_signal
                    
#                     set_trace()
                    
                    dWs[i] = dWs[i] +  np.outer(delta, intermediate_outputs[i])
                    dbiases[i] = dbiases[i] + delta
                    
                    error_signal = np.dot(self.Ws[i].T, delta)     
            
            else: 
                print('backward entering sigmoid part!')
            
                for i in reversed(range(len(self.Ws))):

                    if i == len(self.Ws) - 1:
    #                     print('last layer!')
                        delta = error_signal
                    else:
                        delta = intermediate_outputs[i+1]*(1-intermediate_outputs[i+1]) * error_signal

                    dWs[i] = dWs[i] +  np.outer(delta, intermediate_outputs[i])
                    dbiases[i] = dbiases[i] + delta

                    error_signal = np.dot(self.Ws[i].T, delta)
                
        return dWs, dbiases
    
    def update(self, dWs, dbiases, batch_size, lr): 
        
        for i in range(len(self.Ws)): 
            self.Ws[i] = self.Ws[i] + (dWs[i] * lr) / batch_size 
            self.bs[i] = self.bs[i] + (dbiases[i] * lr) / batch_size
            
            
        
    def train(self, x_train, y_train, lr, epochs, batch_size, print_frequency = 10 ,shuffle_indexes = True):
        
        number_of_batches = int(math.floor(len(x_train)/batch_size))  
        
        print('---Before training---')
        for j in range(len(self.Ws)):
            print(f'Sum of Ws for layer {j}: {np.sum(np.abs(self.Ws[j]))} and sum of bs: {np.sum(np.abs(self.bs[j]))}')
        
        for i in range(epochs): 
            
            if shuffle_indexes: 
                shuffled_idxs = np.random.permutation(X_train.shape[0])
            else: 
                shuffled_idxs = np.array([i for i in range(len(X_train))])
                
                
            for batch in range(0, number_of_batches): 
                
                idxs_current_batch = shuffled_idxs[batch * batch_size : (batch + 1) * batch_size]

                X_batch = X_train[idxs_current_batch]
                y_batch = y_train[idxs_current_batch]


                outputs, intermediate_outputs_list =  self._forward_batch(x0s= X_batch )
                dWs, dbiases = self.backward(x0s = X_batch, outputs = outputs, desired_outputs = y_batch,intermediate_outputs_list = intermediate_outputs_list)
                

                self.update(dWs, dbiases, batch_size, lr)
                
            if (i % print_frequency == 0): 
                print(f'Epoch: {i}')
                for j in range(len(self.Ws)): 
                    print(f'sum of abs dWs for layer {j}: {np.sum(np.abs(dWs[j]))} and sum of dbs: {np.sum(np.abs(dbiases[j]))}')
                    print(f'sum of Ws for layer {j}: {np.sum(np.abs(self.Ws[j]))} and sum of bs: {np.sum(np.abs(self.bs[j]))}')


                y_pred, _ = self._forward_batch(x0s = X_train)
                print(f'MSE on the training set: { np.square((np.array(y_pred) - np.array(y_train))).sum() / np.array(y_pred).shape[0] }')
                    
  

In [17]:
X_train = np.array([[i] for i in range(100)])

y_train = 2 * X_train

In [18]:
our_nn._forward(X_train[15])

(array([74.39682141]),
 [array([15]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([74.39682141])])

In [38]:
our_nn = NeuralNetwork(number_of_layers= 3, number_of_neurons_per_layer= [100, 40, 68], input_size= 1 )

our_nn.train(X_train, y_train, lr = 1e-7, epochs = 5000, batch_size= 100, shuffle_indexes= True)

---Before training---
Sum of Ws for layer 0: 86.3854827902921 and sum of bs: 0.0
Sum of Ws for layer 1: 320.7208905230938 and sum of bs: 0.0
Sum of Ws for layer 2: 340.3759188579585 and sum of bs: 0.0
Sum of Ws for layer 3: 7.150046190977206 and sum of bs: 0.0
Epoch: 0
sum of abs dWs for layer 0: 1529706.6705131067 and sum of dbs: 23060.904580599592
sum of Ws for layer 0: 86.38482165490204 and sum of bs: 2.3060904580599593e-05
sum of abs dWs for layer 1: 65531779.29338612 and sum of dbs: 24803.872347957717
sum of Ws for layer 1: 320.7149032996516 and sum of bs: 2.480387234795771e-05
sum of abs dWs for layer 2: 30615673.943302106 and sum of dbs: 50011.07918227741
sum of Ws for layer 2: 340.3740284821264 and sum of bs: 5.001107918227742e-05
sum of abs dWs for layer 3: 12348558.28491178 and sum of dbs: 13972.459256855345
sum of Ws for layer 3: 7.143626382910938 and sum of bs: 1.3972459256855343e-05
MSE on the training set: 25730.541554902866
Epoch: 10
sum of abs dWs for layer 0: 1199403.0

Epoch: 140
sum of abs dWs for layer 0: 363047.92084198253 and sum of dbs: 5473.045699533591
sum of Ws for layer 0: 86.37101293743467 and sum of bs: 0.0008399500489132632
sum of abs dWs for layer 1: 13330616.4154229 and sum of dbs: 5047.476073104294
sum of Ws for layer 1: 320.7018411108446 and sum of bs: 0.001072771945108966
sum of abs dWs for layer 2: 14088349.025117531 and sum of dbs: 26099.819894361917
sum of Ws for layer 2: 340.45611233758734 and sum of bs: 0.004609170340971886
sum of abs dWs for layer 3: 5747546.173608263 and sum of dbs: 7452.490395874758
sum of Ws for layer 3: 7.063858774910409 and sum of bs: 0.0014096481486808741
MSE on the training set: 7374.954585816248
Epoch: 150
sum of abs dWs for layer 0: 375145.2729355916 and sum of dbs: 5655.3525746246405
sum of Ws for layer 0: 86.37259989007578 and sum of bs: 0.0008509198890337044
sum of abs dWs for layer 1: 13433865.820705123 and sum of dbs: 5086.421118101438
sum of Ws for layer 1: 320.7245531493252 and sum of bs: 0.0011

Epoch: 260
sum of abs dWs for layer 0: 367186.93505670084 and sum of dbs: 5535.351063489692
sum of Ws for layer 0: 86.39633120662367 and sum of bs: 0.0011655971829190447
sum of abs dWs for layer 1: 10262719.391755868 and sum of dbs: 3883.326308138581
sum of Ws for layer 1: 321.0165471042659 and sum of bs: 0.0013891059731192309
sum of abs dWs for layer 2: 8231473.34357765 and sum of dbs: 12589.610821636923
sum of Ws for layer 2: 340.6652537744918 and sum of bs: 0.006849581861749065
sum of abs dWs for layer 3: 3198772.9854796794 and sum of dbs: 3408.1323737844064
sum of Ws for layer 3: 7.2757878178111 and sum of bs: 0.0020542740487649947
MSE on the training set: 1529.2049669670728
Epoch: 270
sum of abs dWs for layer 0: 345075.36320148694 and sum of dbs: 5201.036805027304
sum of Ws for layer 0: 86.3984299450714 and sum of bs: 0.0011942315062719487
sum of abs dWs for layer 1: 9797926.293404542 and sum of dbs: 3707.1883165663157
sum of Ws for layer 1: 321.0407908213467 and sum of bs: 0.0014

Epoch: 380
sum of abs dWs for layer 0: 143934.3717111443 and sum of dbs: 2168.156363495225
sum of Ws for layer 0: 86.41496309550149 and sum of bs: 0.0014637048851797937
sum of abs dWs for layer 1: 3886156.1272028573 and sum of dbs: 1468.4797209958415
sum of Ws for layer 1: 321.2331817672713 and sum of bs: 0.0015942908126983014
sum of abs dWs for layer 2: 2158866.8314894047 and sum of dbs: 3005.0675456447393
sum of Ws for layer 2: 340.80538440998225 and sum of bs: 0.007623384474688269
sum of abs dWs for layer 3: 1096819.8933950413 and sum of dbs: 1033.8385569019279
sum of Ws for layer 3: 7.436130296371164 and sum of bs: 0.0022983761086156043
MSE on the training set: 140.18468727692593
Epoch: 390
sum of abs dWs for layer 0: 128328.47578411791 and sum of dbs: 1932.5321754310098
sum of Ws for layer 0: 86.41584525667703 and sum of bs: 0.0014782401866083256
sum of abs dWs for layer 1: 3488858.4952135836 and sum of dbs: 1316.7462018564
sum of Ws for layer 1: 321.2428988175078 and sum of bs: 0

Epoch: 510
sum of abs dWs for layer 0: 32584.00563603035 and sum of dbs: 491.0168719320023
sum of Ws for layer 0: 86.42144043794788 and sum of bs: 0.0015707809689113846
sum of abs dWs for layer 1: 844315.0772322287 and sum of dbs: 319.1591616950945
sum of Ws for layer 1: 321.3045507430844 and sum of bs: 0.001668805267059063
sum of abs dWs for layer 2: 516029.0132095722 and sum of dbs: 698.3886960732718
sum of Ws for layer 2: 340.8504992612479 and sum of bs: 0.007830182474264685
sum of abs dWs for layer 3: 245900.99869092513 and sum of dbs: 222.9052783080905
sum of Ws for layer 3: 7.487017164266524 and sum of bs: 0.002367497114642818
MSE on the training set: 6.500000365469749
Epoch: 520
sum of abs dWs for layer 0: 28769.271553660674 and sum of dbs: 430.0426130243364
sum of Ws for layer 0: 86.42164422917159 and sum of bs: 0.0015741222832828048
sum of abs dWs for layer 1: 764868.149147746 and sum of dbs: 288.89459031234173
sum of Ws for layer 1: 321.30692169417546 and sum of bs: 0.0016711

Epoch: 630
sum of abs dWs for layer 0: 7530.679967138607 and sum of dbs: 112.33048696198611
sum of Ws for layer 0: 86.42281031363403 and sum of bs: 0.0015931328189869916
sum of abs dWs for layer 1: 200945.29526425988 and sum of dbs: 74.15428634526754
sum of Ws for layer 1: 321.3203691296411 and sum of bs: 0.0016842942146646368
sum of abs dWs for layer 2: 123051.3125071991 and sum of dbs: 162.90799610952277
sum of Ws for layer 2: 340.85993605948454 and sum of bs: 0.00787166837133475
sum of abs dWs for layer 3: 56065.869921629754 and sum of dbs: 50.35092445634797
sum of Ws for layer 3: 7.497532671683527 and sum of bs: 0.0023813622888906637
MSE on the training set: 0.33260164074464216
Epoch: 640
sum of abs dWs for layer 0: 6755.082341341331 and sum of dbs: 100.77832092545005
sum of Ws for layer 0: 86.42285719766173 and sum of bs: 0.0015938991690624786
sum of abs dWs for layer 1: 177731.01573162852 and sum of dbs: 65.47779610704596
sum of Ws for layer 1: 321.32091232623173 and sum of bs: 0

Epoch: 750
sum of abs dWs for layer 0: 1633.231286024785 and sum of dbs: 24.450381148731378
sum of Ws for layer 0: 86.42312107729805 and sum of bs: 0.0015981892369188197
sum of abs dWs for layer 1: 43504.49566984249 and sum of dbs: 16.245643184905433
sum of Ws for layer 1: 321.3239480189355 and sum of bs: 0.0016877890426006408
sum of abs dWs for layer 2: 26862.625764749213 and sum of dbs: 35.21413828274817
sum of Ws for layer 2: 340.86207387984945 and sum of bs: 0.007880909985425476
sum of abs dWs for layer 3: 12515.616272625346 and sum of dbs: 11.149556554915307
sum of Ws for layer 3: 7.499907947999512 and sum of bs: 0.0023844669084091314
MSE on the training set: 0.016515926902191728
Epoch: 760
sum of abs dWs for layer 0: 1426.0789000922737 and sum of dbs: 21.287657583529302
sum of Ws for layer 0: 86.42313154800897 and sum of bs: 0.001598359497133317
sum of abs dWs for layer 1: 39850.58030010062 and sum of dbs: 14.94122297546569
sum of Ws for layer 1: 321.3240692600994 and sum of bs: 

Epoch: 870
sum of abs dWs for layer 0: 363.58333025834764 and sum of dbs: 5.294904074540009
sum of Ws for layer 0: 86.42319038799076 and sum of bs: 0.0015993038298453561
sum of abs dWs for layer 1: 9435.110820128977 and sum of dbs: 3.4594252346085153
sum of Ws for layer 1: 321.3247452105185 and sum of bs: 0.001688566382998647
sum of abs dWs for layer 2: 5876.821787551182 and sum of dbs: 7.445956082583643
sum of Ws for layer 2: 340.86254989457495 and sum of bs: 0.007882927555990965
sum of abs dWs for layer 3: 2781.007145461853 and sum of dbs: 2.4062485827620037
sum of Ws for layer 3: 7.5004370834534875 and sum of bs: 0.0023851491524261945
MSE on the training set: 0.0008177812487023768
Epoch: 880
sum of abs dWs for layer 0: 323.0467427910596 and sum of dbs: 4.682276038313635
sum of Ws for layer 0: 86.42319271855584 and sum of bs: 0.0015993405785180046
sum of abs dWs for layer 1: 8729.37306231973 and sum of dbs: 3.168116234589167
sum of Ws for layer 1: 321.3247720969232 and sum of bs: 0.0

Epoch: 990
sum of abs dWs for layer 0: 81.11017009583047 and sum of dbs: 1.0270334191319914
sum of Ws for layer 0: 86.42320578778198 and sum of bs: 0.00159953784061615
sum of abs dWs for layer 1: 2145.7528722518423 and sum of dbs: 0.6856864618764729
sum of Ws for layer 1: 321.3249222179735 and sum of bs: 0.0016887304888322302
sum of abs dWs for layer 2: 1273.458250900885 and sum of dbs: 1.4164157938527295
sum of Ws for layer 2: 340.86265564868506 and sum of bs: 0.007883350413771893
sum of abs dWs for layer 3: 617.3654229876962 and sum of dbs: 0.4638786178746797
sum of Ws for layer 3: 7.500554606097756 and sum of bs: 0.0023852922064355395
MSE on the training set: 4.3347186524195425e-05
Epoch: 1000
sum of abs dWs for layer 0: 71.23476066808713 and sum of dbs: 0.8792580624745183
sum of Ws for layer 0: 86.42320630583465 and sum of bs: 0.0015995448284967643
sum of abs dWs for layer 1: 1889.3189329993631 and sum of dbs: 0.587909461048179
sum of Ws for layer 1: 321.32492816904767 and sum of b

MSE on the training set: 5.188521100698012e-06
Epoch: 1120
sum of abs dWs for layer 0: 15.830335828154555 and sum of dbs: 0.048467720623793197
sum of Ws for layer 0: 86.42320932252225 and sum of bs: 0.001599576211902222
sum of abs dWs for layer 1: 416.6020985216145 and sum of dbs: 0.03594705142083443
sum of Ws for layer 1: 321.32496281842054 and sum of bs: 0.0016887569439853218
sum of abs dWs for layer 2: 254.58420323971768 and sum of dbs: 0.08470512605598875
sum of Ws for layer 2: 340.86267990784586 and sum of bs: 0.007883422761363645
sum of abs dWs for layer 3: 120.89032172472467 and sum of dbs: 0.018250986798174162
sum of Ws for layer 3: 7.50058157061439 and sum of bs: 0.0023853157766954985
MSE on the training set: 4.749656605632992e-06
Epoch: 1130
sum of abs dWs for layer 0: 13.930654311992882 and sum of dbs: 0.030509795728541435
sum of Ws for layer 0: 86.4232094240998 and sum of bs: 0.0015995763686464403
sum of abs dWs for layer 1: 368.85030261070034 and sum of dbs: 0.026485361128

Epoch: 1260
sum of abs dWs for layer 0: 2.759967609668962 and sum of dbs: 0.15655076041289662
sum of Ws for layer 0: 86.42321003590622 and sum of bs: 0.001599566786851981
sum of abs dWs for layer 1: 71.49779749796578 and sum of dbs: 0.11041915148490224
sum of Ws for layer 1: 321.32497098982157 and sum of bs: 0.001688749457540896
sum of abs dWs for layer 2: 44.895330774931146 and sum of dbs: 0.20391444619397786
sum of Ws for layer 2: 340.8626847861739 and sum of bs: 0.007883410582695429
sum of abs dWs for layer 3: 20.92316933972577 and sum of dbs: 0.07145835104475963
sum of Ws for layer 3: 7.500587004834808 and sum of bs: 0.002385310257337202
MSE on the training set: 3.255264959820873e-06
Epoch: 1270
sum of abs dWs for layer 0: 2.4153544263730096 and sum of dbs: 0.16165451270526005
sum of Ws for layer 0: 86.42321005344392 and sum of bs: 0.0015995655680113947
sum of abs dWs for layer 1: 63.21158781852264 and sum of dbs: 0.11328204290051581
sum of Ws for layer 1: 321.32497119172035 and su

Epoch: 1380
sum of abs dWs for layer 0: 0.6177439289221403 and sum of dbs: 0.1890060477751469
sum of Ws for layer 0: 86.42321015219642 and sum of bs: 0.0015995505868008403
sum of abs dWs for layer 1: 16.57072697877932 and sum of dbs: 0.13111495507201754
sum of Ws for layer 1: 321.32497232070307 and sum of bs: 0.0016887372787404505
sum of abs dWs for layer 2: 9.825041936032346 and sum of dbs: 0.23972472268810366
sum of Ws for layer 2: 340.86268557679887 and sum of bs: 0.0078833857124182
sum of abs dWs for layer 3: 4.667140158996985 and sum of dbs: 0.08604645326155162
sum of Ws for layer 3: 7.500587890382859 and sum of bs: 0.002385300588438295
MSE on the training set: 3.2112111778380447e-06
Epoch: 1390
sum of abs dWs for layer 0: 0.547372344685405 and sum of dbs: 0.19010082797812305
sum of Ws for layer 0: 86.4232101560772 and sum of bs: 0.001599549142931888
sum of abs dWs for layer 1: 14.71698210402409 and sum of dbs: 0.13184862350922738
sum of Ws for layer 1: 321.32497236589836 and sum 

Epoch: 1500
sum of abs dWs for layer 0: 0.13796313485194536 and sum of dbs: 0.19613086670924024
sum of Ws for layer 0: 86.42321017815 and sum of bs: 0.0015995328957120515
sum of abs dWs for layer 1: 3.687484625724854 and sum of dbs: 0.13583301757002347
sum of Ws for layer 1: 321.3249726180027 and sum of bs: 0.0016887240455518682
sum of abs dWs for layer 2: 1.9244710631578328 and sum of dbs: 0.24766043972526552
sum of Ws for layer 2: 340.862685754206 and sum of bs: 0.007883358169590664
sum of abs dWs for layer 3: 1.0404862797816912 and sum of dbs: 0.0893010063672956
sum of Ws for layer 3: 7.5005880880269205 and sum of bs: 0.0023852900190522485
MSE on the training set: 3.208976261593731e-06
Epoch: 1510
sum of abs dWs for layer 0: 0.12170200231637011 and sum of dbs: 0.19637591467708768
sum of Ws for layer 0: 86.4232101790247 and sum of bs: 0.0015995314002061481
sum of abs dWs for layer 1: 3.252847361057409 and sum of dbs: 0.1359973068518649
sum of Ws for layer 1: 321.32497262804645 and su

Epoch: 1620
sum of abs dWs for layer 0: 0.030902380843600523 and sum of dbs: 0.19774369586263082
sum of Ws for layer 0: 86.4232101839288 and sum of bs: 0.001599514871630405
sum of abs dWs for layer 1: 0.8259008596458042 and sum of dbs: 0.13691430661399986
sum of Ws for layer 1: 321.32497268417825 and sum of bs: 0.001688710577325531
sum of abs dWs for layer 2: 0.4307887256056536 and sum of dbs: 0.249666095355248
sum of Ws for layer 2: 340.8626857938583 and sum of bs: 0.007883330034041219
sum of abs dWs for layer 3: 0.2328136581137469 and sum of dbs: 0.09002545382072104
sum of Ws for layer 3: 7.500588131993462 and sum of bs: 0.0023852792485180214
MSE on the training set: 3.2088303181795928e-06
Epoch: 1630
sum of abs dWs for layer 0: 0.027172586189628544 and sum of dbs: 0.19779982700466395
sum of Ws for layer 0: 86.42321018411818 and sum of bs: 0.0015995133649974714
sum of abs dWs for layer 1: 0.7262086819106434 and sum of dbs: 0.13695193735694483
sum of Ws for layer 1: 321.32497268654146

Epoch: 1740
sum of abs dWs for layer 0: 0.007064535060701531 and sum of dbs: 0.19810189385100205
sum of Ws for layer 0: 86.42321018522152 and sum of bs: 0.0015994967740952809
sum of abs dWs for layer 1: 0.18874869176510317 and sum of dbs: 0.13715443317603765
sum of Ws for layer 1: 321.3249726990909 and sum of bs: 0.001688697056927314
sum of abs dWs for layer 2: 0.0982096378205022 and sum of dbs: 0.2501115198845545
sum of Ws for layer 2: 340.86268580268086 and sum of bs: 0.007883301768346338
sum of abs dWs for layer 3: 0.05297955858522093 and sum of dbs: 0.09018634290342407
sum of Ws for layer 3: 7.500588141790221 and sum of bs: 0.002385268433307716
MSE on the training set: 3.208787044092086e-06
Epoch: 1750
sum of abs dWs for layer 0: 0.0062290006458847955 and sum of dbs: 0.19811439243506737
sum of Ws for layer 0: 86.42321018526488 and sum of bs: 0.0015994952649434143
sum of abs dWs for layer 1: 0.16641602947253573 and sum of dbs: 0.1371628106469036
sum of Ws for layer 1: 321.3249726996

Epoch: 1860
sum of abs dWs for layer 0: 0.0017388274664520828 and sum of dbs: 0.19818101116770573
sum of Ws for layer 0: 86.42321018551371 and sum of bs: 0.0015994786602066728
sum of abs dWs for layer 1: 0.04640000329565145 and sum of dbs: 0.13720745121289474
sum of Ws for layer 1: 321.3249727025649 and sum of bs: 0.001688683525040717
sum of abs dWs for layer 2: 0.02390683229354394 and sum of dbs: 0.250209885987523
sum of Ws for layer 2: 340.862685804708 and sum of bs: 0.00788327347363504
sum of abs dWs for layer 3: 0.012802115414231839 and sum of dbs: 0.09022187384110505
sum of Ws for layer 3: 7.500588143985957 and sum of bs: 0.002385257608209004
MSE on the training set: 3.2087488674790977e-06
Epoch: 1870
sum of abs dWs for layer 0: 0.0015499109509779082 and sum of dbs: 0.19818376163319423
sum of Ws for layer 0: 86.42321018552444 and sum of bs: 0.0015994771504989676
sum of abs dWs for layer 1: 0.041350530137707085 and sum of dbs: 0.1372092930971166
sum of Ws for layer 1: 321.324972702

MSE on the training set: 3.208707787297495e-06
Epoch: 2000
sum of abs dWs for layer 0: 0.00043694699514667916 and sum of dbs: 0.19819927197732046
sum of Ws for layer 0: 86.4232101855962 and sum of bs: 0.0015994575231934956
sum of abs dWs for layer 1: 0.01160256807857407 and sum of dbs: 0.13721966393962243
sum of Ws for layer 1: 321.32497270358544 and sum of bs: 0.0016886677348251348
sum of abs dWs for layer 2: 0.0057433618620423696 and sum of dbs: 0.2502325685774911
sum of Ws for layer 2: 340.86268580525854 and sum of bs: 0.007883240456017349
sum of abs dWs for layer 3: 0.0029806610230830454 and sum of dbs: 0.09023006790681894
sum of Ws for layer 3: 7.500588144549753 and sum of bs: 0.002385244976392071
MSE on the training set: 3.2087046282664797e-06
Epoch: 2010
sum of abs dWs for layer 0: 0.0004060975373887902 and sum of dbs: 0.19819963949655095
sum of Ws for layer 0: 86.42321018559898 and sum of bs: 0.0015994560133581388
sum of abs dWs for layer 1: 0.010778005573425271 and sum of dbs:

MSE on the training set: 3.2086667211515488e-06
Epoch: 2130
sum of abs dWs for layer 0: 0.00023008722096482008 and sum of dbs: 0.19820112231305367
sum of Ws for layer 0: 86.42321018562228 and sum of bs: 0.0015994378952222292
sum of abs dWs for layer 1: 0.006073499344310512 and sum of dbs: 0.13722087648496403
sum of Ws for layer 1: 321.3249727039021 and sum of bs: 0.0016886530719199323
sum of abs dWs for layer 2: 0.002857319556110804 and sum of dbs: 0.2502348453395514
sum of Ws for layer 2: 340.8626858054193 and sum of bs: 0.00788320979562108
sum of abs dWs for layer 3: 0.0014201063419136371 and sum of dbs: 0.09023089127277542
sum of Ws for layer 3: 7.500588144675508 and sum of bs: 0.0023852332464049057
MSE on the training set: 3.2086635622672254e-06
Epoch: 2140
sum of abs dWs for layer 0: 0.0002243533569746044 and sum of dbs: 0.19820111120094483
sum of Ws for layer 0: 86.42321018562374 and sum of bs: 0.0015994363853745982
sum of abs dWs for layer 1: 0.005920241418121522 and sum of dbs:

Epoch: 2270
sum of abs dWs for layer 0: 0.00019057269984107327 and sum of dbs: 0.19820035228324318
sum of Ws for layer 0: 86.42321018564107 and sum of bs: 0.001599416757387424
sum of abs dWs for layer 1: 0.005017334616044037 and sum of dbs: 0.13722033006282008
sum of Ws for layer 1: 321.32497270412773 and sum of bs: 0.001688637281083238
sum of abs dWs for layer 2: 0.0023060330368955308 and sum of dbs: 0.25023386160707206
sum of Ws for layer 2: 340.8626858055283 and sum of bs: 0.007883176776699146
sum of abs dWs for layer 3: 0.0011238817195283416 and sum of dbs: 0.09023053701855846
sum of Ws for layer 3: 7.500588144738187 and sum of bs: 0.002385220614099734
MSE on the training set: 3.20861933833289e-06
Epoch: 2280
sum of abs dWs for layer 0: 0.00018963618163318288 and sum of dbs: 0.19820026884990533
sum of Ws for layer 0: 86.42321018564232 and sum of bs: 0.001599415247546007
sum of abs dWs for layer 1: 0.004992303010916936 and sum of dbs: 0.13722027197108627
sum of Ws for layer 1: 321.3

Epoch: 2390
sum of abs dWs for layer 0: 0.00018449060909099635 and sum of dbs: 0.1981992733528817
sum of Ws for layer 0: 86.42321018565579 and sum of bs: 0.0015993986393349692
sum of abs dWs for layer 1: 0.00485477141395031 and sum of dbs: 0.13721958084811375
sum of Ws for layer 1: 321.3249727043036 and sum of bs: 0.001688623746148667
sum of abs dWs for layer 2: 0.002221185305097683 and sum of dbs: 0.25023249746737264
sum of Ws for layer 2: 340.86268580561205 and sum of bs: 0.007883148474908775
sum of abs dWs for layer 3: 0.0010784112970593954 and sum of dbs: 0.09023004520742312
sum of Ws for layer 3: 7.500588144780884 and sum of bs: 0.0023852097864644297
MSE on the training set: 3.208581432593076e-06
Epoch: 2400
sum of abs dWs for layer 0: 0.000184292230385739 and sum of dbs: 0.19819917879208385
sum of Ws for layer 0: 86.42321018565701 and sum of bs: 0.001599397129501826
sum of abs dWs for layer 1: 0.004849469241953162 and sum of dbs: 0.1372195152960321
sum of Ws for layer 1: 321.3249

Epoch: 2510
sum of abs dWs for layer 0: 0.0001832040491506463 and sum of dbs: 0.1981981221350546
sum of Ws for layer 0: 86.42321018567026 and sum of bs: 0.0015993805213853451
sum of abs dWs for layer 1: 0.0048203860212055714 and sum of dbs: 0.13721878316872133
sum of Ws for layer 1: 321.3249727044765 and sum of bs: 0.0016886102112908812
sum of abs dWs for layer 2: 0.0022032435052732253 and sum of dbs: 0.25023104343274344
sum of Ws for layer 2: 340.8626858056941 and sum of bs: 0.007883120173278937
sum of abs dWs for layer 3: 0.0010687982328221146 and sum of dbs: 0.09022952092606566
sum of Ws for layer 3: 7.500588144821676 and sum of bs: 0.0023851989588905926
MSE on the training set: 3.2085435272840867e-06
Epoch: 2520
sum of abs dWs for layer 0: 0.00018316194723076335 and sum of dbs: 0.1981980252192535
sum of Ws for layer 0: 86.42321018567145 and sum of bs: 0.0015993790115609832
sum of abs dWs for layer 1: 0.004819260908395051 and sum of dbs: 0.13721871603775
sum of Ws for layer 1: 321.3

Epoch: 2630
sum of abs dWs for layer 0: 0.00018292997108874915 and sum of dbs: 0.19819695566025824
sum of Ws for layer 0: 86.42321018568465 and sum of bs: 0.001599362403541851
sum of abs dWs for layer 1: 0.004813062848303098 and sum of dbs: 0.13721797526050827
sum of Ws for layer 1: 321.32497270464876 and sum of bs: 0.001688596676512367
sum of abs dWs for layer 2: 0.0021994275751189294 and sum of dbs: 0.2502295704250239
sum of Ws for layer 2: 340.8626858057758 and sum of bs: 0.007883091871814851
sum of abs dWs for layer 3: 0.001066755743450606 and sum of dbs: 0.09022898979158711
sum of Ws for layer 3: 7.500588144862067 and sum of bs: 0.002385188131380187
MSE on the training set: 3.2085056224542635e-06
Epoch: 2640
sum of abs dWs for layer 0: 0.00018292095920214972 and sum of dbs: 0.19819685824542094
sum of Ws for layer 0: 86.42321018568585 and sum of bs: 0.0015993608937263785
sum of abs dWs for layer 1: 0.004812822185647278 and sum of dbs: 0.13721790779497287
sum of Ws for layer 1: 321.

Epoch: 2750
sum of abs dWs for layer 0: 0.00021791384389267788 and sum of dbs: 0.19819525767185867
sum of Ws for layer 0: 86.42321018571874 and sum of bs: 0.0015993442857821286
sum of abs dWs for layer 1: 0.005748135227561942 and sum of dbs: 0.1372168110052041
sum of Ws for layer 1: 321.3249727046832 and sum of bs: 0.0016885831416770677
sum of abs dWs for layer 2: 0.002687520916153499 and sum of dbs: 0.2502274364368308
sum of Ws for layer 2: 340.8626858059117 and sum of bs: 0.00788306357133235
sum of abs dWs for layer 3: 0.0013283455875526535 and sum of dbs: 0.0902282199078701
sum of Ws for layer 3: 7.500588144944735 and sum of bs: 0.0023851773039890896
MSE on the training set: 3.2084677182799074e-06
Epoch: 2760
sum of abs dWs for layer 0: 0.00021365730284978048 and sum of dbs: 0.1981952242919721
sum of Ws for layer 0: 86.42321018572018 and sum of bs: 0.0015993427759792842
sum of abs dWs for layer 1: 0.005634364070747792 and sum of dbs: 0.13721678647165497
sum of Ws for layer 1: 321.32

Epoch: 2870
sum of abs dWs for layer 0: 0.00019026999323459984 and sum of dbs: 0.19819450382533996
sum of Ws for layer 0: 86.42321018573453 and sum of bs: 0.0015993261681765691
sum of abs dWs for layer 1: 0.0050092564387959485 and sum of dbs: 0.1372162797422554
sum of Ws for layer 1: 321.3249727048726 and sum of bs: 0.0016885696070764468
sum of abs dWs for layer 2: 0.0023018494167161493 and sum of dbs: 0.25022647656459823
sum of Ws for layer 2: 340.862685806003 and sum of bs: 0.007883035270240356
sum of abs dWs for layer 3: 0.0011216526052303549 and sum of dbs: 0.0902278741188779
sum of Ws for layer 3: 7.500588144995992 and sum of bs: 0.0023851664766208233
MSE on the training set: 3.2084298143148307e-06
Epoch: 2880
sum of abs dWs for layer 0: 0.00018936933638904913 and sum of dbs: 0.19819441985358832
sum of Ws for layer 0: 86.4232101857358 and sum of bs: 0.0015993246583797108
sum of abs dWs for layer 1: 0.004985183357550444 and sum of dbs: 0.13721622128960778
sum of Ws for layer 1: 321

Epoch: 2990
sum of abs dWs for layer 0: 0.00018442060154450485 and sum of dbs: 0.1981934214217095
sum of Ws for layer 0: 86.42321018574927 and sum of bs: 0.0015993080506589864
sum of abs dWs for layer 1: 0.00485291295586956 and sum of dbs: 0.1372155281996736
sum of Ws for layer 1: 321.32497270504837 and sum of bs: 0.0016885560725414172
sum of abs dWs for layer 2: 0.002220248237893794 and sum of dbs: 0.25022510810628296
sum of Ws for layer 2: 340.86268580608663 and sum of bs: 0.007883006969285417
sum of abs dWs for layer 3: 0.0010779221301345566 and sum of dbs: 0.09022738074782334
sum of Ws for layer 3: 7.500588145038595 and sum of bs: 0.0023851556493051864
MSE on the training set: 3.208391910817781e-06
Epoch: 3000
sum of abs dWs for layer 0: 0.0001842297627775733 and sum of dbs: 0.1981933267501848
sum of Ws for layer 0: 86.42321018575049 and sum of bs: 0.0015993065408704261
sum of abs dWs for layer 1: 0.004847812315828139 and sum of dbs: 0.1372154625734192
sum of Ws for layer 1: 321.32

Epoch: 3110
sum of abs dWs for layer 0: 0.0001831832092155946 and sum of dbs: 0.19819226949751212
sum of Ws for layer 0: 86.4232101857637 and sum of bs: 0.0015992899332443913
sum of abs dWs for layer 1: 0.004819841744189679 and sum of dbs: 0.1372147300474618
sum of Ws for layer 1: 321.3249727052212 and sum of bs: 0.0016885425380832903
sum of abs dWs for layer 2: 0.002202992410534582 and sum of dbs: 0.2502236531938909
sum of Ws for layer 2: 340.86268580616866 and sum of bs: 0.007882978668491261
sum of abs dWs for layer 3: 0.0010686767036640695 and sum of dbs: 0.09022685614938916
sum of Ws for layer 3: 7.500588145079369 and sum of bs: 0.002385144822051108
MSE on the training set: 3.208354007756595e-06
Epoch: 3120
sum of abs dWs for layer 0: 0.0001831425638534751 and sum of dbs: 0.19819217256194294
sum of Ws for layer 0: 86.42321018576493 and sum of bs: 0.0015992884234646172
sum of abs dWs for layer 1: 0.004818755563111668 and sum of dbs: 0.13721466290330073
sum of Ws for layer 1: 321.324

Epoch: 3250
sum of abs dWs for layer 0: 0.00018290298575036478 and sum of dbs: 0.19819090805520617
sum of Ws for layer 0: 86.42321018578052 and sum of bs: 0.0015992687963949312
sum of abs dWs for layer 1: 0.004812354737901026 and sum of dbs: 0.137213787116659
sum of Ws for layer 1: 321.32497270542217 and sum of bs: 0.0016885267479824068
sum of abs dWs for layer 2: 0.0021990920626933598 and sum of dbs: 0.25022193399543186
sum of Ws for layer 2: 340.862685806264 and sum of bs: 0.007882945651107727
sum of abs dWs for layer 3: 0.0010665894062528946 and sum of dbs: 0.09022623624343365
sum of Ws for layer 3: 7.500588145126477 and sum of bs: 0.002385132190334912
MSE on the training set: 3.2083097880986457e-06
Epoch: 3260
sum of abs dWs for layer 0: 0.000182896118922244 and sum of dbs: 0.1981908106109183
sum of Ws for layer 0: 86.4232101857817 and sum of bs: 0.0015992672866255318
sum of abs dWs for layer 1: 0.00481217140962736 and sum of dbs: 0.13721371963144435
sum of Ws for layer 1: 321.3249

Epoch: 3380
sum of abs dWs for layer 0: 0.00018285770187237286 and sum of dbs: 0.198189640626284
sum of Ws for layer 0: 86.42321018579608 and sum of bs: 0.0015992491694506667
sum of abs dWs for layer 1: 0.004811147124643752 and sum of dbs: 0.13721290937102945
sum of Ws for layer 1: 321.3249727056086 and sum of bs: 0.0016885120858431543
sum of abs dWs for layer 2: 0.002198468866530675 and sum of dbs: 0.2502203335771665
sum of Ws for layer 2: 340.8626858063524 and sum of bs: 0.007882914992312142
sum of abs dWs for layer 3: 0.0010662582379711721 and sum of dbs: 0.09022565916454645
sum of Ws for layer 3: 7.500588145170139 and sum of bs: 0.0023851204609619944
MSE on the training set: 3.20826872753641e-06
Epoch: 3390
sum of abs dWs for layer 0: 0.00018285664310059514 and sum of dbs: 0.19818954309661896
sum of Ws for layer 0: 86.42321018579726 and sum of bs: 0.0015992476596909237
sum of abs dWs for layer 1: 0.004811119037560972 and sum of dbs: 0.1372128418285878
sum of Ws for layer 1: 321.324

sum of abs dWs for layer 1: 0.004810898611129251 and sum of dbs: 0.1372120988223788
sum of Ws for layer 1: 321.3249727057807 and sum of bs: 0.001688498551644013
sum of abs dWs for layer 2: 0.0021983457486847674 and sum of dbs: 0.25021885567073576
sum of Ws for layer 2: 340.862685806434 and sum of bs: 0.007882886692059516
sum of abs dWs for layer 3: 0.0010661948627289104 and sum of dbs: 0.09022512626060479
sum of Ws for layer 3: 7.500588145210429 and sum of bs: 0.002385109633915135
MSE on the training set: 3.2082308259373677e-06
Epoch: 3510
sum of abs dWs for layer 0: 0.0001828477666097147 and sum of dbs: 0.1981883726733579
sum of Ws for layer 0: 86.42321018581164 and sum of bs: 0.0015992295426319617
sum of abs dWs for layer 1: 0.004810884330227278 and sum of dbs: 0.13721203127426299
sum of Ws for layer 1: 321.32497270579495 and sum of bs: 0.0016884974237976926
sum of abs dWs for layer 2: 0.002198338844423011 and sum of dbs: 0.2502187325074175
sum of Ws for layer 2: 340.8626858064408 an

Epoch: 3640
sum of abs dWs for layer 0: 0.00018284356631456704 and sum of dbs: 0.1981871046426701
sum of Ws for layer 0: 86.42321018582722 and sum of bs: 0.001599209915938838
sum of abs dWs for layer 1: 0.004810774823400895 and sum of dbs: 0.13721115312554072
sum of Ws for layer 1: 321.3249727059814 and sum of bs: 0.0016884827618460392
sum of abs dWs for layer 2: 0.0021982888348725266 and sum of dbs: 0.2502171313411213
sum of Ws for layer 2: 340.8626858065292 and sum of bs: 0.007882853675309357
sum of abs dWs for layer 3: 0.0010661674033176957 and sum of dbs: 0.09022450450124565
sum of Ws for layer 3: 7.5005881452574314 and sum of bs: 0.002385097002441293
MSE on the training set: 3.2081866079692724e-06
Epoch: 3650
sum of abs dWs for layer 0: 0.0001828432749439885 and sum of dbs: 0.19818700710176126
sum of Ws for layer 0: 86.4232101858284 and sum of bs: 0.0015992084061984151
sum of abs dWs for layer 1: 0.0048107672478674875 and sum of dbs: 0.1372110855755883
sum of Ws for layer 1: 321.3

Epoch: 3760
sum of abs dWs for layer 0: 0.00018284048725953484 and sum of dbs: 0.19818593414735444
sum of Ws for layer 0: 86.42321018584158 and sum of bs: 0.001599191799102806
sum of abs dWs for layer 1: 0.004810695073310207 and sum of dbs: 0.1372103425232254
sum of Ws for layer 1: 321.3249727061534 and sum of bs: 0.001688469227820084
sum of abs dWs for layer 2: 0.002198253807532858 and sum of dbs: 0.25021565333482404
sum of Ws for layer 2: 340.8626858066108 and sum of bs: 0.007882825375418859
sum of abs dWs for layer 3: 0.0010661512389457395 and sum of dbs: 0.09022397156122028
sum of Ws for layer 3: 7.50058814529772 and sum of bs: 0.0023850861755329955
MSE on the training set: 3.2081487073459317e-06
Epoch: 3770
sum of abs dWs for layer 0: 0.00018284023643598606 and sum of dbs: 0.19818583660606248
sum of Ws for layer 0: 86.42321018584278 and sum of bs: 0.0015991902893713003
sum of abs dWs for layer 1: 0.004810688581534904 and sum of dbs: 0.1372102749730288
sum of Ws for layer 1: 321.32

Epoch: 3880
sum of abs dWs for layer 0: 0.00018283804582158288 and sum of dbs: 0.19818476364883503
sum of Ws for layer 0: 86.42321018585595 and sum of bs: 0.0015991736823737816
sum of abs dWs for layer 1: 0.004810632365782048 and sum of dbs: 0.13720953191891472
sum of Ws for layer 1: 321.3249727063255 and sum of bs: 0.0016884556938740625
sum of abs dWs for layer 2: 0.0021982276759338845 and sum of dbs: 0.25021417532467494
sum of Ws for layer 2: 340.8626858066924 and sum of bs: 0.0078827970756955
sum of abs dWs for layer 3: 0.001066139842089716 and sum of dbs: 0.09022343861979823
sum of Ws for layer 3: 7.500588145338009 and sum of bs: 0.0023850753486886513
MSE on the training set: 3.2081108071582776e-06
Epoch: 3890
sum of abs dWs for layer 0: 0.00018283797358903178 and sum of dbs: 0.19818466610599622
sum of Ws for layer 0: 86.42321018585716 and sum of bs: 0.0015991721726511929
sum of abs dWs for layer 1: 0.004810630647496758 and sum of dbs: 0.13720946436769377
sum of Ws for layer 1: 321

Epoch: 4000
sum of abs dWs for layer 0: 0.00018283688408386614 and sum of dbs: 0.1981835931389473
sum of Ws for layer 0: 86.42321018587032 and sum of bs: 0.0015991555657517652
sum of abs dWs for layer 1: 0.004810603862808066 and sum of dbs: 0.13720872130713485
sum of Ws for layer 1: 321.32497270649753 and sum of bs: 0.0016884421600079753
sum of abs dWs for layer 2: 0.0021982193982419667 and sum of dbs: 0.2502126973005211
sum of Ws for layer 2: 340.86268580677404 and sum of bs: 0.007882768776139283
sum of abs dWs for layer 3: 0.0010661380137662515 and sum of dbs: 0.0902229056733122
sum of Ws for layer 3: 7.500588145378295 and sum of bs: 0.0023850645219082598
MSE on the training set: 3.20807290741332e-06
Epoch: 4010
sum of abs dWs for layer 0: 0.00018283665987580506 and sum of dbs: 0.19818349559855292
sum of Ws for layer 0: 86.42321018587153 and sum of bs: 0.001599154056038094
sum of abs dWs for layer 1: 0.0048105980824214595 and sum of dbs: 0.13720865375756555
sum of Ws for layer 1: 321

Epoch: 4120
sum of abs dWs for layer 0: 0.00018283548494341068 and sum of dbs: 0.19818242263881206
sum of Ws for layer 0: 86.4232101858847 and sum of bs: 0.0015991374492367579
sum of abs dWs for layer 1: 0.00481056901435683 and sum of dbs: 0.13720791070204624
sum of Ws for layer 1: 321.32497270666966 and sum of bs: 0.0016884286262218214
sum of abs dWs for layer 2: 0.002198207808265782 and sum of dbs: 0.2502112192886277
sum of Ws for layer 2: 340.86268580685567 and sum of bs: 0.007882740476750204
sum of abs dWs for layer 3: 0.0010661344102276082 and sum of dbs: 0.09022237273124929
sum of Ws for layer 3: 7.500588145418581 and sum of bs: 0.002385053695191822
MSE on the training set: 3.2080350081498448e-06
Epoch: 4130
sum of abs dWs for layer 0: 0.00018283538385225972 and sum of dbs: 0.19818232509721587
sum of Ws for layer 0: 86.42321018588589 and sum of bs: 0.0015991359395320039
sum of abs dWs for layer 1: 0.004810566524718056 and sum of dbs: 0.13720784315168388
sum of Ws for layer 1: 321

Epoch: 4240
sum of abs dWs for layer 0: 0.00018283424044944735 and sum of dbs: 0.1981812521440474
sum of Ws for layer 0: 86.42321018589907 and sum of bs: 0.0015991193328287576
sum of abs dWs for layer 1: 0.004810538299347109 and sum of dbs: 0.13720710010071108
sum of Ws for layer 1: 321.32497270684166 and sum of bs: 0.0016884150925156008
sum of abs dWs for layer 2: 0.0021981983757490818 and sum of dbs: 0.2502097412835457
sum of Ws for layer 2: 340.8626858069373 and sum of bs: 0.007882712177528268
sum of abs dWs for layer 3: 0.001066131962911131 and sum of dbs: 0.09022183979164128
sum of Ws for layer 3: 7.500588145458866 and sum of bs: 0.002385042868539337
MSE on the training set: 3.2079971093043555e-06
Epoch: 4250
sum of abs dWs for layer 0: 0.00018283406674451404 and sum of dbs: 0.198181154603997
sum of Ws for layer 0: 86.42321018590027 and sum of bs: 0.0015991178231329211
sum of abs dWs for layer 1: 0.004810533868839593 and sum of dbs: 0.13720703255139777
sum of Ws for layer 1: 321.3

Epoch: 4360
sum of abs dWs for layer 0: 0.0001828328556399285 and sum of dbs: 0.19818008165768372
sum of Ws for layer 0: 86.42321018591343 and sum of bs: 0.0015991012165277646
sum of abs dWs for layer 1: 0.004810503833859088 and sum of dbs: 0.13720628950516092
sum of Ws for layer 1: 321.32497270701367 and sum of bs: 0.0016884015588893135
sum of abs dWs for layer 2: 0.0021981869854765567 and sum of dbs: 0.25020826328904344
sum of Ws for layer 2: 340.86268580701886 and sum of bs: 0.007882683878473466
sum of abs dWs for layer 3: 0.0010661284663232916 and sum of dbs: 0.0902213068558493
sum of Ws for layer 3: 7.500588145499149 and sum of bs: 0.0023850320419508044
MSE on the training set: 3.207959210917399e-06
Epoch: 4370
sum of abs dWs for layer 0: 0.00018283265731432126 and sum of dbs: 0.19817998411853047
sum of Ws for layer 0: 86.42321018591461 and sum of bs: 0.001599099706840845
sum of abs dWs for layer 1: 0.0048104987452711615 and sum of dbs: 0.13720622195646187
sum of Ws for layer 1: 3

Epoch: 4480
sum of abs dWs for layer 0: 0.00018283181039422243 and sum of dbs: 0.19817891117274192
sum of Ws for layer 0: 86.4232101859278 and sum of bs: 0.0015990831003337785
sum of abs dWs for layer 1: 0.00481047844439827 and sum of dbs: 0.13720547891071694
sum of Ws for layer 1: 321.3249727071858 and sum of bs: 0.0016883880253429587
sum of abs dWs for layer 2: 0.002198180332592034 and sum of dbs: 0.25020678529644225
sum of Ws for layer 2: 340.86268580710043 and sum of bs: 0.007882655579585804
sum of abs dWs for layer 3: 0.0010661275086407368 and sum of dbs: 0.09022077392073853
sum of Ws for layer 3: 7.500588145539435 and sum of bs: 0.0023850212154262244
MSE on the training set: 3.2079213129674535e-06
Epoch: 4490
sum of abs dWs for layer 0: 0.00018283178614626028 and sum of dbs: 0.19817881363196865
sum of Ws for layer 0: 86.423210185929 and sum of bs: 0.0015990815906557763
sum of abs dWs for layer 1: 0.004810478008652466 and sum of dbs: 0.1372054113609445
sum of Ws for layer 1: 321.3

Epoch: 4600
sum of abs dWs for layer 0: 0.00018283071707359534 and sum of dbs: 0.19817774069660146
sum of Ws for layer 0: 86.42321018594218 and sum of bs: 0.0015990649842467985
sum of abs dWs for layer 1: 0.004810451769915906 and sum of dbs: 0.13720466832232658
sum of Ws for layer 1: 321.3249727073578 and sum of bs: 0.001688374491876536
sum of abs dWs for layer 2: 0.0021981730088531416 and sum of dbs: 0.2502053073149189
sum of Ws for layer 2: 340.862685807182 and sum of bs: 0.007882627280865277
sum of abs dWs for layer 3: 0.001066126191381934 and sum of dbs: 0.09022024098962367
sum of Ws for layer 3: 7.500588145579721 and sum of bs: 0.002385010388965596
MSE on the training set: 3.207883415478005e-06
Epoch: 4610
sum of abs dWs for layer 0: 0.0001828305410382917 and sum of dbs: 0.19817764315804026
sum of Ws for layer 0: 86.42321018594336 and sum of bs: 0.0015990634745777135
sum of abs dWs for layer 1: 0.004810447277110169 and sum of dbs: 0.13720460077404997
sum of Ws for layer 1: 321.324

Epoch: 4720
sum of abs dWs for layer 0: 0.00018283003625375015 and sum of dbs: 0.19817657022040014
sum of Ws for layer 0: 86.42321018595653 and sum of bs: 0.0015990468682668237
sum of abs dWs for layer 1: 0.004810436120965986 and sum of dbs: 0.1372038577340482
sum of Ws for layer 1: 321.3249727075299 and sum of bs: 0.001688360958490045
sum of abs dWs for layer 2: 0.0021981714401108814 and sum of dbs: 0.25020382933345237
sum of Ws for layer 2: 340.86268580726363 and sum of bs: 0.007882598982311887
sum of abs dWs for layer 3: 0.001066127958399946 and sum of dbs: 0.09021970805852386
sum of Ws for layer 3: 7.500588145620008 and sum of bs: 0.00238499956256892
MSE on the training set: 3.207845518431698e-06
Epoch: 4730
sum of abs dWs for layer 0: 0.00018282997070165737 and sum of dbs: 0.19817647268070343
sum of Ws for layer 0: 86.42321018595773 and sum of bs: 0.001599045358606656
sum of abs dWs for layer 1: 0.004810434581219921 and sum of dbs: 0.13720379018502302
sum of Ws for layer 1: 321.32

Epoch: 4840
sum of abs dWs for layer 0: 0.00018282890104648065 and sum of dbs: 0.19817539975733361
sum of Ws for layer 0: 86.42321018597087 and sum of bs: 0.0015990287523938546
sum of abs dWs for layer 1: 0.00481040832684118 and sum of dbs: 0.13720304715472872
sum of Ws for layer 1: 321.32497270770193 and sum of bs: 0.0016883474251834863
sum of abs dWs for layer 2: 0.0021981635317615674 and sum of dbs: 0.2502023513684525
sum of Ws for layer 2: 340.8626858073452 and sum of bs: 0.007882570683925633
sum of abs dWs for layer 3: 0.0010661263277540458 and sum of dbs: 0.0902191751333664
sum of Ws for layer 3: 7.500588145660295 and sum of bs: 0.002384988736236195
MSE on the training set: 3.207807621844486e-06
Epoch: 4850
sum of abs dWs for layer 0: 0.00018282879834395256 and sum of dbs: 0.19817530221932497
sum of Ws for layer 0: 86.42321018597207 and sum of bs: 0.0015990272427426036
sum of abs dWs for layer 1: 0.0048104057941058456 and sum of dbs: 0.13720297960684802
sum of Ws for layer 1: 321

Epoch: 4960
sum of abs dWs for layer 0: 0.00018282747861473082 and sum of dbs: 0.19817422930656825
sum of Ws for layer 0: 86.42321018598521 and sum of bs: 0.0015990106366278894
sum of abs dWs for layer 1: 0.004810372855564677 and sum of dbs: 0.13720223658380926
sum of Ws for layer 1: 321.32497270787394 and sum of bs: 0.0016883338919568575
sum of abs dWs for layer 2: 0.0021981516160074896 and sum of dbs: 0.25020087341888264
sum of Ws for layer 2: 340.86268580742683 and sum of bs: 0.007882542385706513
sum of abs dWs for layer 3: 0.0010661225493486508 and sum of dbs: 0.0902186422137769
sum of Ws for layer 3: 7.500588145700583 and sum of bs: 0.0023849779099674204
MSE on the training set: 3.207769725691332e-06
Epoch: 4970
sum of abs dWs for layer 0: 0.0001828273442164494 and sum of dbs: 0.1981741317696921
sum of Ws for layer 0: 86.4232101859864 and sum of bs: 0.0015990091269855555
sum of abs dWs for layer 1: 0.004810369475647765 and sum of dbs: 0.13720216903670052
sum of Ws for layer 1: 321

In [35]:
y_pred, intermediate = our_nn._forward_batch(x0s = X_train)

In [36]:
y_pred

[array([0.00533396]),
 array([2.00542893]),
 array([4.00534492]),
 array([6.0052609]),
 array([8.00517688]),
 array([10.00509287]),
 array([12.00500885]),
 array([14.00492484]),
 array([16.00484082]),
 array([18.00475681]),
 array([20.00467279]),
 array([22.00458877]),
 array([24.00450476]),
 array([26.00442074]),
 array([28.00433673]),
 array([30.00425271]),
 array([32.0041687]),
 array([34.00408468]),
 array([36.00400066]),
 array([38.00391665]),
 array([40.00383263]),
 array([42.00374862]),
 array([44.0036646]),
 array([46.00358059]),
 array([48.00349657]),
 array([50.00341255]),
 array([52.00332854]),
 array([54.00324452]),
 array([56.00316051]),
 array([58.00307649]),
 array([60.00299248]),
 array([62.00290846]),
 array([64.00282444]),
 array([66.00274043]),
 array([68.00265641]),
 array([70.0025724]),
 array([72.00248838]),
 array([74.00240437]),
 array([76.00232035]),
 array([78.00223633]),
 array([80.00215232]),
 array([82.0020683]),
 array([84.00198429]),
 array([86.00190027])

In [ ]:
-7.355385292240312, -7.43845899976959

In [ ]:
y_pred, intermediate = our_nn._forward_batch(x0s = X_train)

In [ ]:
y_pred

In [ ]:
our_unn = NeuralNetwork(number_of_layers= 3, number_of_neurons_per_layer= [200, 33, 128])

In [ ]:
x0s =  [[0 for i in range(58)], [1 for i in range(58)]]

desired_outputs = [0,1]

outputs, intermediate_outputs_list =  our_unn._forward_batch(x0s= x0s )

In [ ]:
len(our_unn.bs)

In [ ]:
output

In [ ]:
dWs, dbiases = our_unn.backward(x0s, outputs, desired_outputs,intermediate_outputs_list )

In [ ]:
len(dWs), len(dbiases)

In [ ]:
# INITIALISE THE PARAMETERS OF YOUR NEURAL NETWORK AND...
# PLEASE CONSIDER TO USE A MASK OF ONE FOR THE ACTION MADE AND ZERO OTHERWISE IF YOU ARE NOT USING VANILLA GRADIENT DESCENT...
# WE SUGGEST A NETWORK WITH ONE HIDDEN LAYER WITH SIZE 200. 


S,X,allowed_a=env.Initialise_game()
N_a=np.shape(allowed_a)[0]   # TOTAL NUMBER OF POSSIBLE ACTIONS

N_in=np.shape(X)[0]    ## INPUT SIZE
N_h=200                ## NUMBER OF HIDDEN NODES


## INITALISE YOUR NEURAL NETWORK...


# HYPERPARAMETERS SUGGESTED (FOR A GRID SIZE OF 4)

epsilon_0 = 0.2     # STARTING VALUE OF EPSILON FOR THE EPSILON-GREEDY POLICY
beta = 0.00005      # THE PARAMETER SETS HOW QUICKLY THE VALUE OF EPSILON IS DECAYING (SEE epsilon_f BELOW)
gamma = 0.85        # THE DISCOUNT FACTOR
eta = 0.0035        # THE LEARNING RATE

N_episodes = 100000 # THE NUMBER OF GAMES TO BE PLAYED 

# SAVING VARIABLES
R_save = np.zeros([N_episodes, 1])
N_moves_save = np.zeros([N_episodes, 1])


In [ ]:
# TRAINING LOOP BONE STRUCTURE...
# I WROTE FOR YOU A RANDOM AGENT (THE RANDOM AGENT WILL BE SLOWER TO GIVE CHECKMATE THAN AN OPTIMISED ONE, 
# SO DON'T GET CONCERNED BY THE TIME IT TAKES), CHANGE WITH YOURS ...

for n in range(N_episodes):

    epsilon_f = epsilon_0 / (1 + beta * n)   ## DECAYING EPSILON
    Done=0                                   ## SET DONE TO ZERO (BEGINNING OF THE EPISODE)
    i = 1                                    ## COUNTER FOR NUMBER OF ACTIONS
    
    S,X,allowed_a=env.Initialise_game()      ## INITIALISE GAME
    print(f'Episode number: {n}')            ## REMOVE THIS OF COURSE, WE USED THIS TO CHECK THAT IT WAS RUNNING.  - Glad to hear.
    
    while Done==0:                           ## START THE EPISODE
        
        
        ## THIS IS A RANDOM AGENT, CHANGE IT...
        
        a,_=np.where(allowed_a==1)
        a_agent=np.random.permutation(a)[0]

                
        S_next,X_next,allowed_a_next,R,Done=env.OneStep(a_agent)
        
        ## THE EPISODE HAS ENDED, UPDATE...BE CAREFUL, THIS IS THE LAST STEP OF THE EPISODE
        if Done==1:
            
            
            break
        
        
        
        
        # IF THE EPISODE IS NOT OVER...
        else:
            
            ## ONLY TO PUT SUMETHING
            PIPPO=1
            
            
        # NEXT STATE AND CO. BECOME ACTUAL STATE...     
        S=np.copy(S_next)
        X=np.copy(X_next)
        allowed_a=np.copy(allowed_a_next)
        
        i += 1  # UPDATE COUNTER FOR NUMBER OF ACTIONS

        
        
    
    